### PR TITLE
CI/CD: Update Python >=3.9 and <=3.13

### PR DESCRIPTION
**Pull request by kentrutan**
Tests that ran OK 2 days ago are now failing on Python 3.8 on Windows when there have been no changes to tested code. Since Python 3.8 is end of life, let's bump min Python to 3.9 and max to 3.13 and see how it tests out.

### CODE REVIEW

**Comment by kentrutan** [comment]
Tests pass. Looks like it's a go with your approval @jackvreeken.

**Review by jackvreeken — APPROVED** [review]
Not sure if the precommit changes were intended or coupled to 3.13, but otherwise approved 👍

**Comment by kentrutan** [comment]
> Not sure if the precommit changes were intended or coupled to 3.13, but otherwise approved 👍

An update to black was needed to support Python 3.13. I decided to go ahead and update flake8 to latest while I was in there.

**Comment by kentrutan** [comment]
Sorry I just realized that I should have split out the formatting only changes into a separate commit so we could add to .git-blame-ignore-revs. Not going to change now that it is merged. Please help me remember to do this @jackvreeken if you notice.

**Pull request merged**
