### PR TITLE
CI/CD: Fix tox issues and bump Python version

### LINKED ISSUE #250: CI/CD: tox issues with MSL and Python 3.5
Some issues I should have caught earlier, but just got tox up and running on my local machine.

Getting the following flake8 errors from newly added Modelica Standard Library code when running tox:
```
flake8 run-test: commands[0] | flake8
./test/libraries/MSL-4.0.x/Modelica/Resources/Documentation/Generate-ReleaseNotes.py:13:1: I100 Import statements are in the wrong order. 'import json' should be before 'import requests' and in a different group.
[...]
./test/libraries/MSL-4.0.x/.CI/classCoverage/CountClasses.py:15:7: E111 indentation is not a multiple of 4

```
There are also some Python 3.5 incompatibilities with newer typing syntax:

```
py35 run-test: commands[0] | pytest test
=========================================================================================================================================== test session starts ===========================================================================================================================================
platform darwin -- Python 3.5.6, pytest-6.1.2, py-1.11.0, pluggy-0.13.1
cachedir: .tox/py35/.pytest_cache
rootdir: /Users/rutanwk/modelica/pymoca
collected 1 item / 6 errors                                                                                                                                                                                                                                                                               

================================================================================================================================================= ERRORS ==================================================================================================================================================
____________________________________________________________________________________________________________________________________ ERROR collecting test/ast_test.py ____________________________________________________________________________________________________________________________________
.tox/py35/lib/python3.5/site-packages/_pytest/python.py:571: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
.tox/py35/lib/python3.5/site-packages/_pytest/pathlib.py:517: in import_path
    importlib.import_module(module_name)
.tox/py35/lib/python3.5/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:985: in _gcd_import
    ???
<frozen importlib._bootstrap>:968: in _find_and_load
    ???
<frozen importlib._bootstrap>:957: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:673: in _load_unlocked
    ???
.tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
test/ast_test.py:4: in <module>
    from pymoca import ast
E     File "/Users/rutanwk/modelica/pymoca/.tox/py35/lib/python3.5/site-packages/pymoca/ast.py", line 596
E       import_ : Union[ImportClause, ComponentRef] = self.imports[component_ref.name]
E               ^
E   SyntaxError: invalid syntax
[...]
```

### PR DESCRIPTION
**Pull request by kentrutan**
This fixes #250 which are some issues identified by tox (which I just got up and running on my machine):

- Some Python scripts in the newly-added Modelica Standard Library submodules were triggering flake8 errors, so excluded them
- Typing syntax incompatible with Python 3.5 were reverted to type comments

### CODE REVIEW

**Comment by jackvreeken** [comment]
With Python 3.5 having reached end of life 2+ years ago, I'd say it's more than OK to bump the minimum version requirement to 3.7

**Comment by kentrutan** [comment]
@jackvreeken Was working on it, but you are quicker than me! Thanks!

**Comment by jackvreeken** [comment]
No worries :) 
I think I'm about done with playing around over on #257 . Do you want to update your branch of _this_ PR to that commit (and then merge)?

**Comment by kentrutan** [comment]
It will be several hours before I can get to it. If the CI fail is bothering you, then go ahead with your DELME PR and we can just close my old, stale one.

**Comment by jackvreeken** [comment]
No rush, you go ahead and do it in a few hours then. And as far as things bothering me, mostly Casadi still being on 3.9 ;)

**Comment by kentrutan** [comment]
I chose to leave in the Python 3.5 compatibility changes even though we are bumping the min required version to 3.7. I'm hoping to reduce future merge grief.

**Comment by kentrutan** [comment]
@jackvreeken wrote:
> And as far as things bothering me, mostly Casadi still being on 3.9 ;)

Good to see there are some nightly builds for later Python versions: https://github.com/casadi/casadi/issues/3014#issuecomment-1440344236

**Pull request merged**
