### PR TITLE
Switch from setup.py to pyproject.toml

### PR DESCRIPTION
**Pull request by jackvreeken**
- [x] Merge #313 first

### CODE REVIEW

**Review by kentrutan — APPROVED** [review]
I pushed a couple commits with my suggested changes. Thought it would be easier than review comments.

**Comment by kentrutan** [comment]
Second rerun of failed CI didn't work this time. I'll try a 3rd.

**Comment by kentrutan** [comment]
Third time's a charm for the CI. 

@jackvreeken let me know if you are OK with my changes and I will squash the "cruft" commit and merge.

**Comment by jackvreeken** [comment]
Looks good to me! I actually prefer the separate commits (so the 3 we have right now), because then it's easy to see the changes. If we _both_ move to a new file _and_ change lines, it's harder to diff. So as far as I'm concerned you can go ahead and merge the PR as-is, assuming you have other changes you want to make.

**Pull request merged**
