### PR TITLE
Various speedups

### PR DESCRIPTION
**Pull request by jackvreeken**
- [x] Merge #138 first (this goes on top)
- [x] Variable.aliases should be a set as well if we do not guarantee order of canonical variables and its aliases
- [x] Update tests with aliases to compare sets instead of list
- [ ] Test with many RTC-Tools models

### CODE REVIEW

**Comment by jackvreeken** [comment]
@jbaayen @vdwees : Comments would be much welcomed

Notable "breaking" changes that I would like comments on:
- `canonical_variables` is now a set instead of an OrderedSet
- `aliases()` returns a set instead of an OrderedSet
- `__iter__`   no longer loops in a guaranteed order (because of the OrderedSet -> set change)

Major difference between sets and OrderedSets is (1) order and (2) indexibility (`my_set[5]`).

Other discussions:
- I find it somewhat confusing that `__iter__` returns the aliases _without_ the canonical state, whereas there is no such function to ask for something like that directly yourself (before, and now). You would have to drop the canonical state from whatever aliases() returns yourself.

**Comment by jbaayen** [comment]
Did you check that dropping guaranteed order does not break things elsewhere? 

Typical use case: Loop over canonical variables, creating an optimization variable vector. Post-optimization, loop again and extract. If we can get two different orderings here, simple use cases like this will break.

**Comment by jackvreeken** [comment]
I haven't encountered any test cases that fail. The AliasRelation is typically not used to loop over. The only case I could find was in `model.py`. On the RTC-Tools side open would loop over the dae's states/controls/etc (which remains the same as before), and possibly over AliasDicts. Note that AliasDicts do not provide any order guarantees when looping either.

I am not against waiting a little with this speed-up until we have more models/real-life use cases.

Keeping order is relatively simple by using OrderedDicts instead (which have a fast C implementation in recent version of CPython), and not assigning the values. It's a bit weird to return an instance of `odict_keys` instead of `set` though.

**Comment by jbaayen** [comment]
I remember that when I first implemented this, I spent a substantial amount time debugging until I found out that there were some order assumptions in RTC. That's when I switched to OrderedDict.

Since we call it an Alias**Relation** I'm not opposed to dropping order, but we need to be sure we're not breaking anything.

**Pull request merged**
