### PR TITLE
Readme and examples updates

### LINKED ISSUE #326: sympy.Functions in Spring.ipynb
https://github.com/pymoca/pymoca/blob/9d597d76aa2b82bd3d563d4938a098af8baafd49/test/notebooks/Spring.ipynb#L1463

raises

```txt
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[32], [line 2](vscode-notebook-cell:?execution_count=32&line=2)
      [1](vscode-notebook-cell:?execution_count=32&line=1) v_x, spring_k, t, V, x = sympy.symbols('v_x, spring.k, t, V, x')
----> [2](vscode-notebook-cell:?execution_count=32&line=2) V_eq = (v_x(t)**2 + spring_k*x(t)**2)/2
      [3](vscode-notebook-cell:?execution_count=32&line=3) sympy.Eq(V, V_eq)

TypeError: 'Symbol' object is not callable
```

### PR DESCRIPTION
**Pull request by kentrutan**
Update the README and check/fix examples and scripts in preparation for another release.

- [x] Add overview about current development state to README and update install and roadmap sections
- [x] Test/fix CasADi and SymPy notebook examples linked in the README

EDIT: Removing the tasks below to focus on getting the README updated sooner rather than later.

- [ ] Update create_conda_env.sh to work with the ANTLR 4.13.1 update and fix other install issues
- [ ] Test create_conda_env.sh on macOS
- [ ] Test create_conda_env.sh on Linux, or better yet, create a test and skip on Windows

Closes #326

### CODE REVIEW

**Comment by jackvreeken** [comment]
I assume blocked by https://github.com/pymoca/pymoca/pull/294 (as you're committing on top of it)

**Comment by kentrutan** [comment]
> I assume blocked by #294 (as you're committing on top of it)

Yes it was on top of #294 because it depends on it. 

Can you explain the purpose of the BLOCKED label on the PR? I don't understand. Doesn't GitHub automatically take care of this by letting you know that it needs to be rebased? Also, it is a draft pull request anyway with tasks left to do.

**Comment by jackvreeken** [comment]
Oh, that's just a label I use for convenience. I also quite often make MRs that are on top of other MRs for whatever reason. And then I want to make clear to myself and others that this is the case, and that I (or someone else) don't accidentally merge the wrong one first. You're right that, because it was a draft, it wasn't as relevant.

**Comment by kentrutan** [comment]
Changed this branch to focus on the README. Someone mentioned Pymoca in a Hacker News comment, so I wanted to at least get this merged. Also thinking about tagging a release to pick up the latest updates. I see some issues with the older ANTLR and Python 3.13 (and possibly others).

**Comment by kentrutan** [comment]
After review of the README by a non-expert friend, I have some updates to make, so I'm converting this back into draft.

**Comment by jackvreeken** [comment]
Looks much better to me, happy to see the conda-specific instructions and the TODO section go. Eventually I think it would be nice to have some comparisons to other compilers (Dymola and OpenModelica?), mostly for "when to use which".

**Review by jackvreeken — APPROVED** [review]

**Comment by kentrutan** [comment]
Decided to go ahead and update the CasADi and SymPy notebook examples and removed the broken XML example.

**Pull request merged**
