### PR TITLE
CasADi: Fix caching of delay expression with constant delay

### PR DESCRIPTION
**Pull request by jackvreeken**
Closes #270

### CODE REVIEW

**Review by kentrutan — CHANGES_REQUESTED** [review]
Thanks for jumping on this! Nice use of `itertools`!

It looks like you need to fetch and rebase this on master. Also, I'm getting an error in `test_delay` in my test environment in Python 3.9.0 and CasADi 3.6.2:
```
test/gen_casadi_test.py:65: in assert_model_equivalent_numeric
    self.assertEqual(len(A.alg_states), len(B.alg_states))
E   AssertionError: 2 != 3
```

**Comment by jackvreeken** [comment]
Why are the Github Actions not running?

**Comment by kentrutan** [comment]
I did get a notice ahead of time from GitHub on the 60 day deactivation for my fork. It's super easy to reply to the email keep it going. Who is GitHub contacting for the main repo?

**Comment by jackvreeken** [comment]
Not me, at least I cannot find any emails from GitHub about this in my mailbox. Maybe they contacted James Goppert, as the owner of the Pymoca organization? Either way it's a bit more nuanced than a personal repo I imagine.

Either way, if the current changes look good to you, feel free to merge!

**Comment by kentrutan** [comment]
Changes look good to me, for what it's worth.

**Comment by kentrutan** [comment]
@jgoppert are you getting emails about pymoca CI deactivation from GitHub? If so, do you want to transfer or share ownership (or whatever) of the pymoca organization to @jackvreeken and/or me so you are not bugged? Also, do you mind if we change some of the PyPI metadata to reflect the current situation with regards to maintainers, etc?

**Pull request merged**
