### PR TITLE
Add compiler tool options

### PR DESCRIPTION
**Pull request by kentrutan**
Update the compiler tool and add options to support the SymPy backend in addition to CasADi in the previous version. Hopefully this will make it easier to use Pymoca without having to resort to python scripting. I know the SymPy backend is not being actively developed, but I wanted to support at least two for starters. The xml backend could be easily added if that would be useful to anyone. For more info, see the comment on 38d44c2

Since I do not have experience with CasADi, it would be great of someone who does could try this out in an actual workflow.

The longer-term intention is to make it easier to add backends to the compiler tool and incorporate more options to support planned improvements to parse Modelica libraries.

This pull request also includes a commit with new notebook that I used for testing the SymPy output from the test case model Spring.mo. It is a copy/paste/modify of the Spring.ipynb.

### CODE REVIEW

**Comment by kentrutan** [comment]
I improved the error messages a bit for various settings of verbosity. See 443f9de

**Comment by jackvreeken** [comment]
- What does this sentence mean? I think there's a typo in there, but can't quickly figure out where " Also, now need to have use -v flag to get the exception stack trace." 
- For you other commits, could you vaguely precede the commit message with what part of Pymoca it affects? See commit log for some examples ("SymPy: Add ...").
- Great job at directly adding tests/example functionality!

Those were about my comments, contents look good to me :)

**Comment by jackvreeken** [comment]
Is this PR ready to merge now?

**Comment by jackvreeken** [comment]
No worries, I marked it as WIP for now in the title, so that I don't get confused :)

**Comment by kentrutan** [comment]
Thanks for your patience and guidance! FYI, I will be working on this quite a bit more this year. I'm going to finally get that `import` statement code PR done soon, but I'm learning that chopping up the Caterpillar open source code into bite-sized, more general PRs is more of a challenge than I initially thought. But we're getting there bit by bit!

**Comment by kentrutan** [comment]
I think I'm done now. Please take a look and see if you think the two new commits are OK to merge.

**Comment by jackvreeken** [comment]
Next time around, I would prefer 2 additional small commits over "This commit also includes changes to  ..." (MyPy / gitignore). That said, you did actually mentioned these changes in the commit message, instead of silently including them. Not wanting to make you do even more work of restructuring the commits, I just merged it :)

**Comment by kentrutan** [comment]
Thanks for going ahead with the merge. I am chopping things up a little better for the upcoming import statement PR.

Thanks for the collaborator invite. Still would like you in the loop looking at my contributions for a while if possible. I hope you have the time :)

**Comment by jackvreeken** [comment]
Definitely still want to be in the loop :) I'm not even sure if "write" permissions allow you to merge to master, but at least you should be able to make new (feature) branches in this repository.

**Pull request merged**
