### PR TITLE
Fix expansion of MX equations

### PR DESCRIPTION
**Pull request by jackvreeken**
According to Joris Gillis (CasADi co-author), ca.matrix_expand() is
broken and will not be fixed. Instead, we will then rely on regular
.expand() functionality to turn MX into SX, without the "graceful"
fallback that ca.matrix_expand() was supposed to offer. From initial
tests, it seems that most/all commonly used functionality is supported
by .expand().

### CODE REVIEW

**Comment by vdwees** [comment]
should expand be made default?

**Comment by jackvreeken** [comment]
- [ ] Update CasADi depency in requirements.txt

1. We have to wait with merging until the version of CasADi on PyPI supports empty SXFunctions (i.e. no outputs). This is why the builds are currently failing.
2. Expanding should not be the default. MXFunctions are generally more compact than SXFunctions, and it's always easy to call .expand() to go from MX to SX. There is no way to go reverse from SX -> MX, so I'd rather keep it as is.
3. When serializable/picklable SXFunctions arrive in a PyPI version of CasADi—but this version does _not_ yet support pickling MXFunctions—I'll make `cache=True` imply `expand_mx=True` for the time being (and raise a warning/info message stating so). Expanding and caching will be decoupled again when support for pickling MXFunctions arrives in CasADi.
4. Related to (3); `codegen` and `cache` will become separate options. The former overrules the latter, but note that codegen can already work with both `expand_mx=True` and `expand_mx=False` (whereas `cache` will have to wait for picklable MXFunctions).

**Comment by jackvreeken** [comment]
- [ ] Wait until CasADi 3.4.0 is released

**Comment by jgoppert** [comment]
Can you fix the conflicts and rebase when you get a chance?

**Comment by jackvreeken** [comment]
Apparently my other WIP was already merged (?), which was not supposed to happen before this one got merged.

**Comment by vdwees** [comment]
for some reason #57 was merged before this one, so these changes are already incorporated. As I reviewed and approved both, I think we might as we as close this one.

**Comment by jgoppert** [comment]
That was my fault, was trying to get as many PR's as I could merged last night and didn't know these were dependent on eachother.

**Pull request closed without merging**
